# Generated by Django 6.0.3 on 2026-03-09 18:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255)),
                ('description_ru', models.TextField()),
                ('description_uz', models.TextField()),
                ('olympiad_type', models.CharField(choices=[('online', 'Онлайн (Бесплатно)'), ('offline', 'Офлайн (Платно)')], db_index=True, default='online', max_length=10)),
                ('price', models.BigIntegerField(default=0, help_text='Цена в UZS (целое число)')),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_participants', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('participant', 'Участник')], default='participant', max_length=20)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=255)),
                ('grade', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)])),
                ('participant_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('olympiad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.olympiad')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField()),
                ('text_uz', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('options', models.JSONField(help_text="Формат: [{'id': 'A', 'text': '...'}, ...]")),
                ('correct_option', models.CharField(help_text='A, B, C или D', max_length=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('answers_json', models.JSONField(help_text='Сырые ответы пользователя для анализа')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.olympiad')),
            ],
            options={
                'verbose_name': 'Результат экзамена',
                'verbose_name_plural': 'Результаты экзаменов',
                'unique_together': {('user', 'olympiad')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('free', 'Бесплатно'), ('expired', 'Бронь истекла')], db_index=True, default='pending', max_length=10)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.olympiad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'indexes': [models.Index(fields=['payment_status', 'payment_deadline'], name='core_regist_payment_5d517e_idx')],
                'unique_together': {('user', 'olympiad')},
            },
        ),
    ]
