# Generated by Django 4.2.29 on 2026-06-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('payme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='ID транзакции Click')),
                ('click_paydoc_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID платежного документа Click')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'Initiating'), (2, 'Successfully'), (-2, 'Canceled after successful performed'), (-1, 'Canceled during initiation')], default=0, verbose_name='Статус')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина отмены/Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменено в')),
                ('performed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Выполнено в')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Отменено в')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_transactions', to='core.registration', verbose_name='Регистрация')),
            ],
            options={
                'verbose_name': 'CLICK Transaction',
                'verbose_name_plural': 'CLICK Transactions',
                'db_table': 'click_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'Initiating'), (2, 'Successfully'), (-2, 'Canceled after successful performed'), (-1, 'Canceled during initiation')], default=0)),
                ('fiscal_data', models.JSONField(default=dict)),
                ('cancel_reason', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('performed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Payme Transaction',
                'verbose_name_plural': 'Payme Transactions',
                'db_table': 'payme_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='olympiad',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='sub_olympiad',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='sub_olympiad_grade',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Olympiad',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='registration',
            name='olympiad',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='smssenthistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='smssenthistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subolympiad',
            name='olympiad',
        ),
        migrations.AlterUniqueTogether(
            name='subolympiadgrade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subolympiadgrade',
            name='sub_olympiad',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='olympiad',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sub_olympiad',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sub_olympiad_grade',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='SMSSentHistory',
        ),
        migrations.DeleteModel(
            name='SubOlympiad',
        ),
        migrations.DeleteModel(
            name='SubOlympiadGrade',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
