# Generated by Django 4.2.29 on 2026-06-03 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='ID транзакции Click')),
                ('click_paydoc_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID платежного документа Click')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'Initiating'), (2, 'Successfully'), (-2, 'Canceled after successful performed'), (-1, 'Canceled during initiation')], default=0, verbose_name='Статус')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина отмены/Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Изменено в')),
                ('performed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Выполнено в')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Отменено в')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_transactions', to='core.registration', verbose_name='Регистрация')),
            ],
            options={
                'verbose_name': 'CLICK Transaction',
                'verbose_name_plural': 'CLICK Transactions',
                'db_table': 'click_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
