# Generated by Django 6.0.3 on 2026-03-24 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания регистрации'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Макс. количество участников (0 - без лимита)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
