# Generated by Django 4.2.29 on 2026-03-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_olympiad_registration_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='registration_end_datetime',
        ),
    ]
