# Generated by Django 4.2.29 on 2026-06-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clicktransactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickTransactions',
        ),
    ]
