# Generated by Django 4.2.29 on 2026-06-03 13:28

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_clicktransactions_paymetransactions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Администратор'), ('participant', 'Участник')], default='participant', max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('participant_id', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('password_text', models.CharField(blank=True, help_text='Stored plain password for admin visibility', max_length=255, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('teachers', models.JSONField(blank=True, default=list, help_text="List of teachers: [{'name': '...', 'phone': '...'}]")),
                ('last_activity', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('answers_json', models.JSONField(blank=True, help_text='Сырые ответы пользователя для анализа', null=True)),
                ('tab_switches', models.PositiveIntegerField(default=0, help_text='Количество переключений вкладок')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Результат экзамена',
                'verbose_name_plural': 'Результаты экзаменов',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('message_uz', models.TextField(blank=True, null=True)),
                ('message_ru', models.TextField(blank=True, null=True)),
                ('message_en', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('info', 'Инфо'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('payment', 'Оплата')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('olympiad_type', models.CharField(choices=[('online', 'Онлайн (Бесплатно)'), ('offline', 'Офлайн (Платно)')], db_index=True, default='online', max_length=10)),
                ('price', models.BigIntegerField(default=0, help_text='Цена в UZS (целое число)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатно')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, default=60, null=True)),
                ('registration_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания регистрации')),
                ('max_participants', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Макс. количество участников (0 - без лимита)')),
                ('is_active', models.BooleanField(default=True)),
                ('grades', models.JSONField(blank=True, default=list)),
                ('region_ids', models.JSONField(blank=True, default=list)),
                ('is_started', models.BooleanField(default=False, verbose_name='Запущена вручную')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('generate_unique_id', models.BooleanField(default=False, verbose_name='Генерировать уникальный ID участника')),
                ('unique_id_prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Префикс уникального ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('options', models.JSONField(help_text="Формат: [{'id': 'A', 'text': '...'}, ...]")),
                ('correct_option', models.CharField(help_text='A, B, C или D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('free', 'Бесплатно'), ('expired', 'Бронь истекла')], db_index=True, default='pending', max_length=10)),
                ('price', models.BigIntegerField(default=0)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('unique_participant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Уникальный ID участника для этой олимпиады')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.olympiad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.CreateModel(
            name='SMSSentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(db_index=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История отправки СМС',
                'verbose_name_plural': 'История отправки СМС',
                'unique_together': {('user', 'template_id')},
            },
        ),
        migrations.CreateModel(
            name='SubOlympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='core.olympiad')),
            ],
            options={
                'verbose_name': 'Предмет олимпиады',
                'verbose_name_plural': 'Предметы олимпиады',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubOlympiadGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(db_index=True, max_length=10, verbose_name='Класс')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_started', models.BooleanField(default=False, verbose_name='Запущена')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_sessions', to='core.subolympiad')),
            ],
            options={
                'verbose_name': 'Сессия предмета для класса',
                'verbose_name_plural': 'Сессии предметов для классов',
                'ordering': ['grade'],
                'unique_together': {('sub_olympiad', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В процессе'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тикет техподдержки',
                'verbose_name_plural': 'Тикеты техподдержки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('olympiad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.olympiad')),
                ('sub_olympiad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.subolympiad')),
                ('sub_olympiad_grade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.subolympiadgrade')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ на тикет',
                'verbose_name_plural': 'Ответы на тикеты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='early_bird, top_score, regular, etc.', max_length=50)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'unique_together': {('user', 'type')},
            },
        ),
        migrations.RemoveField(
            model_name='clicktransactions',
            name='registration',
        ),
        migrations.DeleteModel(
            name='PaymeTransactions',
        ),
        migrations.DeleteModel(
            name='ClickTransactions',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.test'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.olympiad'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='sub_olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.subolympiad'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='sub_olympiad_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.subolympiadgrade'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['payment_status', 'payment_deadline'], name='core_regist_payment_5d517e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user', 'olympiad')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('user', 'olympiad', 'sub_olympiad_grade')},
        ),
    ]
