# Generated by Django 6.0.3 on 2026-04-10 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.olympiad'),
        ),
        migrations.AlterField(
            model_name='test',
            name='olympiad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.olympiad'),
        ),
        migrations.CreateModel(
            name='SubOlympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_started', models.BooleanField(default=False, verbose_name='Запущена вручную')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='core.olympiad')),
            ],
            options={
                'verbose_name': 'Суб-олимпиада',
                'verbose_name_plural': 'Суб-олимпиады',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='examresult',
            name='sub_olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.subolympiad'),
        ),
        migrations.AddField(
            model_name='test',
            name='sub_olympiad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.subolympiad'),
        ),
    ]
