# Generated by Django 6.0.3 on 2026-03-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_middle_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
