# Generated by Django 4.2.29 on 2026-03-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_olympiad_registration_end_date_and_more'),
        ('core', '0003_remove_olympiad_registration_end_datetime'),
    ]

    operations = [
    ]
