# Generated by Django 4.2.29 on 2026-04-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_phone'),
        ('core', '0004_merge_20260325_1844'),
    ]

    operations = [
    ]
