# Generated by Django 4.2.29 on 2026-06-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_examresult_notification_olympiad_question_and_more'),
        ('core', '0004_merge_20260603_1332'),
    ]

    operations = [
    ]
