# Generated by Django 6.0.3 on 2026-04-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_examresult_olympiad_alter_test_olympiad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
