# Generated by Django 6.0.3 on 2026-03-18 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name='Запущена вручную'),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='early_bird, top_score, regular, etc.', max_length=50)),
                ('title_ru', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'unique_together': {('user', 'type')},
            },
        ),
    ]
