# Generated by Django 6.0.3 on 2026-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='grades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='region_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
