# Generated by Django 4.2.29 on 2026-06-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0004_merge_20260603_1332'),
        ('payme', '0005_merge_20260603_1332'),
    ]

    operations = [
    ]
