# Generated by Django 6.0.3 on 2026-03-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_olympiad_grades_olympiad_region_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатно'),
        ),
    ]
