# Generated by Django 6.0.3 on 2026-04-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_olympiad_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='tab_switches',
            field=models.PositiveIntegerField(default=0, help_text='Количество переключений вкладок'),
        ),
    ]
