# Generated by Django 6.0.3 on 2026-04-13 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examresult_tab_switches'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('user', 'olympiad', 'sub_olympiad')},
        ),
        migrations.AddField(
            model_name='examresult',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='answers_json',
            field=models.JSONField(blank=True, help_text='Сырые ответы пользователя для анализа', null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
