# Generated by Django 6.0.3 on 2026-03-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_olympiad_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
