# Generated by Django 4.2.29 on 2026-04-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0003_alter_user_phone_0004_merge_20260325_1844'),
        ('core', '0007_alter_examresult_unique_together_and_more'),
    ]

    operations = [
    ]
