# Generated by Django 6.0.3 on 2026-04-19 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_examresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Олимпиада', 'verbose_name_plural': 'Олимпиады'},
        ),
        migrations.AlterModelOptions(
            name='subolympiad',
            options={'ordering': ['created_at'], 'verbose_name': 'Предмет олимпиады', 'verbose_name_plural': 'Предметы олимпиады'},
        ),
        migrations.RemoveField(
            model_name='subolympiad',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='subolympiad',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='subolympiad',
            name='is_started',
        ),
        migrations.RemoveField(
            model_name='subolympiad',
            name='start_datetime',
        ),
        migrations.CreateModel(
            name='SubOlympiadGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(db_index=True, max_length=10, verbose_name='Класс')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_started', models.BooleanField(default=False, verbose_name='Запущена')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_sessions', to='core.subolympiad')),
            ],
            options={
                'verbose_name': 'Сессия предмета для класса',
                'verbose_name_plural': 'Сессии предметов для классов',
                'ordering': ['grade'],
                'unique_together': {('sub_olympiad', 'grade')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='sub_olympiad_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.subolympiadgrade'),
        ),
        migrations.AddField(
            model_name='test',
            name='sub_olympiad_grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='core.subolympiadgrade'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('user', 'olympiad', 'sub_olympiad_grade')},
        ),
    ]
