# Generated by Django 4.2.29 on 2026-06-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0006_merge_20260603_1336'),
        ('payme', '0007_merge_20260603_1337'),
    ]

    operations = [
    ]
