# Generated by Django 4.2.29 on 2026-04-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_olympiad_options_alter_subolympiad_options_and_more'),
        ('core', '0008_merge_20260419_1824'),
    ]

    operations = [
    ]
