# Generated by Django 4.2.29 on 2026-05-21 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20260422_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В процессе'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тикет техподдержки',
                'verbose_name_plural': 'Тикеты техподдержки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='olympiad',
            name='generate_unique_id',
            field=models.BooleanField(default=False, verbose_name='Генерировать уникальный ID участника'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='unique_id_prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Префикс уникального ID'),
        ),
        migrations.AddField(
            model_name='registration',
            name='unique_participant_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Уникальный ID участника для этой олимпиады'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_text',
            field=models.CharField(blank=True, help_text='Stored plain password for admin visibility', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='teachers',
            field=models.JSONField(blank=True, default=list, help_text="List of teachers: [{'name': '...', 'phone': '...'}]"),
        ),
        migrations.AlterField(
            model_name='subolympiad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subolympiadgrade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='support/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ на тикет',
                'verbose_name_plural': 'Ответы на тикеты',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SMSSentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(db_index=True, max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История отправки СМС',
                'verbose_name_plural': 'История отправки СМС',
                'unique_together': {('user', 'template_id')},
            },
        ),
    ]
