# Generated by Django 4.2.29 on 2026-05-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_smssenthistory'),
        ('core', '0010_supportticket_olympiad_generate_unique_id_and_more'),
    ]

    operations = [
    ]
